### PR TITLE
Sync the code from path-mapped-storage

### PR DESCRIPTION
**Pull request by sswguo**

### CODE REVIEW

**Comment by ruhan1** [comment]
I think we should not copy code from the pathmap lib, but use the lib as dependency. I expect some services will use the storage service, but the slimed indy (or in future, content-retrieval-service) will still use the lib. in future, we might decommission the lib, and all use the service. but until then, it is better to keep using it as a lib. @ligangty wdyt?

**Comment by ligangty** [comment]
@ruhan1 I think most hard part is to solve the inter-deps problems, which may cause some CDI dependency problem in quarkus framework. If the pathmap-storage lib is simple enough and does not have heavy deps on other projects(like weft or something similar), directly using it is not a bad idea. Maybe we can have a try firstly to refer it directly and see if any CDI or deps problems will happen. @sswguo wdyt?

**Comment by ligangty** [comment]
BTW, for what I did, I did not refer weft in repository-service yet because its CDI usage causes some compilation error in quarkus. Maybe we should check that later. But I used atlas directly because it does not import any CDI deps problems yet.

**Comment by ruhan1** [comment]
Yeah, from the beginning I avoid using CDI in this lib. I search it and find one place using a weft threadfactory but we can easily remove it.

**Comment by ruhan1** [comment]
I add a pr to the pathmap lib to completely remove dep on weft. https://github.com/Commonjava/path-mapped-storage/pull/80

**Comment by sswguo** [comment]
@ligangty @ruhan1 yeah, the pathmap lib looks fine for the inter-deps issue, except the weft one ruhan just mentioned above, and it's easy to replace it. I agree to keep it as a lib for now. Closing :)

**Pull request closed without merging**
